In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [2]:
df = pd.read_csv('vehicles.csv')

# Display information about the data

In [3]:
df.head()

id                                                url  \
0  7222695916  https://prescott.craigslist.org/cto/d/prescott...   
1  7218891961  https://fayar.craigslist.org/ctd/d/bentonville...   
2  7221797935  https://keys.craigslist.org/cto/d/summerland-k...   
3  7222270760  https://worcester.craigslist.org/cto/d/west-br...   
4  7210384030  https://greensboro.craigslist.org/cto/d/trinit...   

                   region                         region_url  price  year  \
0                prescott    https://prescott.craigslist.org   6000   NaN   
1            fayetteville       https://fayar.craigslist.org  11900   NaN   
2            florida keys        https://keys.craigslist.org  21000   NaN   
3  worcester / central MA   https://worcester.craigslist.org   1500   NaN   
4              greensboro  https://greensboro.craigslist.org   4900   NaN   

  manufacturer model condition cylinders  ... size  type paint_color  \
0          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
1          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
2          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
3          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   
4          NaN   NaN       NaN       NaN  ...  NaN   NaN         NaN   

  image_url description county state lat long posting_date  
0       NaN         NaN    NaN    az NaN  NaN          NaN  
1       NaN         NaN    NaN    ar NaN  NaN          NaN  
2       NaN         NaN    NaN    fl NaN  NaN          NaN  
3       NaN         NaN    NaN    ma NaN  NaN          NaN  
4       NaN         NaN    NaN    nc NaN  NaN          NaN  

[5 rows x 26 columns]

In [4]:
df.isna().sum()


id                   0
url                  0
region               0
region_url           0
price                0
year              1205
manufacturer     17646
model             5277
condition       174104
cylinders       177678
fuel              3013
odometer          4400
title_status      8242
transmission      2556
VIN             161042
drive           130567
size            306361
type             92858
paint_color     130203
image_url           68
description         70
county          426880
state                0
lat               6549
long              6549
posting_date        68
dtype: int64

In [5]:
df.describe()

id         price           year      odometer  county  \
count  4.268800e+05  4.268800e+05  425675.000000  4.224800e+05     0.0   
mean   7.311487e+09  7.519903e+04    2011.235191  9.804333e+04     NaN   
std    4.473170e+06  1.218228e+07       9.452120  2.138815e+05     NaN   
min    7.207408e+09  0.000000e+00    1900.000000  0.000000e+00     NaN   
25%    7.308143e+09  5.900000e+03    2008.000000  3.770400e+04     NaN   
50%    7.312621e+09  1.395000e+04    2013.000000  8.554800e+04     NaN   
75%    7.315254e+09  2.648575e+04    2017.000000  1.335425e+05     NaN   
max    7.317101e+09  3.736929e+09    2022.000000  1.000000e+07     NaN   

                 lat           long  
count  420331.000000  420331.000000  
mean       38.493940     -94.748599  
std         5.841533      18.365462  
min       -84.122245    -159.827728  
25%        34.601900    -111.939847  
50%        39.150100     -88.432600  
75%        42.398900     -80.832039  
max        82.390818     173.885502

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            426880 non-null  int64  
 1   url           426880 non-null  object 
 2   region        426880 non-null  object 
 3   region_url    426880 non-null  object 
 4   price         426880 non-null  int64  
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  object 
 7   model         421603 non-null  object 
 8   condition     252776 non-null  object 
 9   cylinders     249202 non-null  object 
 10  fuel          423867 non-null  object 
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  object 
 13  transmission  424324 non-null  object 
 14  VIN           265838 non-null  object 
 15  drive         296313 non-null  object 
 16  size          120519 non-null  object 
 17  type          334022 non-null  object 
 18  pain

In [7]:
df.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'county', 'state', 'lat', 'long',
       'posting_date'],
      dtype='object')

In [8]:
df.dtypes

id                int64
url              object
region           object
region_url       object
price             int64
year            float64
manufacturer     object
model            object
condition        object
cylinders        object
fuel             object
odometer        float64
title_status     object
transmission     object
VIN              object
drive            object
size             object
type             object
paint_color      object
image_url        object
description      object
county          float64
state            object
lat             float64
long            float64
posting_date     object
dtype: object

# Data cleaning

In [9]:
df=df.drop(["id","url","image_url","region_url","lat","long","county"],axis = 1)

In [10]:
df_object = df.select_dtypes(include = 'object').head(3) 
df_num = df.select_dtypes(exclude = 'object').head(3)

In [11]:
df.select_dtypes(exclude = 'object').isna().sum()

price          0
year        1205
odometer    4400
dtype: int64

In [12]:
df.select_dtypes(include = 'object').isna().sum()

region               0
manufacturer     17646
model             5277
condition       174104
cylinders       177678
fuel              3013
title_status      8242
transmission      2556
VIN             161042
drive           130567
size            306361
type             92858
paint_color     130203
description         70
state                0
posting_date        68
dtype: int64

In [13]:
df.dropna(subset = ["model"],inplace = True)
df.dropna(subset = ["fuel"],inplace = True)
df.dropna(subset = ["transmission"],inplace = True)
df.dropna(subset = ["title_status"],inplace = True)
df.dropna(subset = ["posting_date"],inplace = True)

In [14]:
df.select_dtypes(include = 'object').isna().sum()

region               0
manufacturer     16764
model                0
condition       164850
cylinders       171086
fuel                 0
title_status         0
transmission         0
VIN             157280
drive           122837
size            291571
type             89085
paint_color     119557
description          2
state                0
posting_date         0
dtype: int64

In [15]:
df.select_dtypes(exclude = 'object').isna().sum()

price          0
year         737
odometer    3508
dtype: int64

In [16]:
df.dropna(subset = ["year"],inplace = True)
df.dropna(subset = ["odometer"],inplace = True)


In [17]:
df.select_dtypes(exclude = 'object').isna().sum()

price       0
year        0
odometer    0
dtype: int64

In [18]:
df["price"].index

Index([    27,     28,     29,     30,     31,     32,     33,     34,     35,
           36,
       ...
       426870, 426871, 426872, 426873, 426874, 426875, 426876, 426877, 426878,
       426879],
      dtype='int64', length=405594)

In [19]:
(405594 * (7.5/100)) 

30419.55

In [20]:
df[df["price"] ==0].head(5)

region  price    year manufacturer              model  condition  \
46       auburn      0  2011.0         jeep            compass  excellent   
126      auburn      0  2018.0    chevrolet  express cargo van   like new   
127      auburn      0  2019.0    chevrolet  express cargo van   like new   
128      auburn      0  2018.0    chevrolet  express cargo van   like new   
191  birmingham      0  2015.0       nissan             sentra  excellent   

       cylinders fuel  odometer title_status transmission                VIN  \
46           NaN  gas   99615.0        clean    automatic                NaN   
126  6 cylinders  gas   68472.0        clean    automatic  1GCWGAFP8J1309579   
127  6 cylinders  gas   69125.0        clean    automatic  1GCWGAFP4K1214373   
128  6 cylinders  gas   66555.0        clean    automatic  1GCWGAFPXJ1337903   
191  4 cylinders  gas   99505.0        clean    automatic  3N1AB7AP8FY348505   

    drive       size   type paint_color  \
46    NaN  full-size    SUV         NaN   
126   rwd  full-size    van       white   
127   rwd  full-size    van       white   
128   rwd  full-size    van       white   
191   fwd        NaN  sedan      silver   

                                           description state  \
46   Call or text now 800-213-0336 Open 9:00-6:00pm...    al   
126  2018 Chevrolet Express Cargo Van RWD 2500 135"...    al   
127  2019 Chevrolet Express Cargo Van RWD 2500 135"...    al   
128  2018 Chevrolet Express Cargo Van RWD 2500 135"...    al   
191  2015 Nissan Sentra  by Benton Nissan of Oxford...    al   

                 posting_date  
46   2021-04-30T16:35:11-0500  
126  2021-04-12T11:20:35-0500  
127  2021-04-12T11:20:00-0500  
128  2021-04-12T11:19:58-0500  
191  2021-05-04T11:00:42-0500

In [21]:
top_30419 = df_num['price'].nlargest(30419)
bottom_100 = df_num['price'].nsmallest(30419)


In [22]:
x=df[(df["price"] <= 3736928711) & (df["price"] >= 1111111)].index
y=df[df["price"] ==0].index

In [23]:
df=df.drop(x,axis = 0)

In [24]:
df=df.drop(y,axis = 0)

In [25]:
df.describe()

price           year      odometer
count   375717.000000  375717.000000  3.757170e+05
mean     18935.740640    2011.096118  9.849603e+04
std      16144.694868       9.385032  1.976752e+05
min          1.000000    1900.000000  0.000000e+00
25%       7200.000000    2008.000000  3.812300e+04
50%      15499.000000    2013.000000  8.703700e+04
75%      27882.000000    2017.000000  1.356360e+05
max    1000000.000000    2022.000000  1.000000e+07

In [26]:
print(df['price'].mean())
print(df['price'].median())

18935.740639896518
15499.0


In [27]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer     14714
model                0
condition       142243
cylinders       153971
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147590
drive           112905
size            267055
type             82507
paint_color     106661
description          2
state                0
posting_date         0
dtype: int64

# manufacturer

In [28]:
df["manufacturer"].unique()

array(['gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa-romeo',
       'subaru', nan, 'acura', 'hyundai', 'mercedes-benz', 'bmw',
       'mitsubishi', 'volkswagen', 'porsche', 'kia', 'ferrari', 'mini',
       'pontiac', 'fiat', 'rover', 'tesla', 'saturn', 'mercury',
       'harley-davidson', 'datsun', 'aston-martin', 'land rover'],
      dtype=object)

In [29]:
df["manufacturer"].isna().sum()

np.int64(14714)

In [30]:
df["manufacturer"]=df["manufacturer"].fillna("Unknown")

In [31]:
df["manufacturer"].isna().sum()

np.int64(0)

In [32]:
df["manufacturer"].unique()

array(['gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa-romeo',
       'subaru', 'Unknown', 'acura', 'hyundai', 'mercedes-benz', 'bmw',
       'mitsubishi', 'volkswagen', 'porsche', 'kia', 'ferrari', 'mini',
       'pontiac', 'fiat', 'rover', 'tesla', 'saturn', 'mercury',
       'harley-davidson', 'datsun', 'aston-martin', 'land rover'],
      dtype=object)

# condition

In [33]:
df["condition"]=df["condition"].fillna("UN")
df["condition"].isna().sum()

np.int64(0)

In [34]:
df["condition"].unique()

array(['good', 'excellent', 'fair', 'like new', 'UN', 'new', 'salvage'],
      dtype=object)

In [35]:
prices = list(df["price"])
condition = list(df["condition"])

In [36]:
len(prices) == len(condition)

True

In [37]:
df["price"].describe()

count     375717.000000
mean       18935.740640
std        16144.694868
min            1.000000
25%         7200.000000
50%        15499.000000
75%        27882.000000
max      1000000.000000
Name: price, dtype: float64

In [38]:
df["condition"].info()

<class 'pandas.core.series.Series'>
Index: 375717 entries, 27 to 426879
Series name: condition
Non-Null Count   Dtype 
--------------   ----- 
375717 non-null  object
dtypes: object(1)
memory usage: 5.7+ MB


In [39]:
condition[230239]

'good'

In [40]:
o=0
for i in condition:
    
    if i == 'UN':
        if prices[o] <= 1000000.0:
            condition[o] = condition[o].replace('UN',"new")
        elif  prices[o] <=27882.00:
            condition[o] = condition[o].replace('UN',"like new")
        elif  prices[o] <= 18935.0:
            condition[o] = condition[o].replace('UN',"excellent")
        elif  prices[o] <=13995.0:
            condition[o] = condition[o].replace('UN',"good")
        elif  prices[o] <=5995.0:
            condition[o] = condition[o].replace('UN',"fair")
        else :
            condition[o] = condition[o].replace("UN","salvage")
    o+=1


In [41]:
test_2=pd.Series(condition)

In [42]:
test_2.unique()

array(['good', 'excellent', 'fair', 'like new', 'new', 'salvage'],
      dtype=object)

In [43]:
df=df.drop(["condition"],axis=1)

In [44]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer         0
model                0
cylinders       153971
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147590
drive           112905
size            267055
type             82507
paint_color     106661
description          2
state                0
posting_date         0
dtype: int64

In [45]:
index =list(df.index)

In [46]:
test_3=pd.DataFrame(condition,index=index,columns=["condition"])

In [47]:
df=pd.concat([df,test_3],axis=1)

In [48]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer         0
model                0
cylinders       153971
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147590
drive           112905
size            267055
type             82507
paint_color     106661
description          2
state                0
posting_date         0
condition            0
dtype: int64

# cylinders

In [49]:
df["cylinders"]=df["cylinders"].fillna("UN")
df["cylinders"].isna().sum()

np.int64(0)

In [50]:
df["cylinders"].unique()

array(['8 cylinders', '6 cylinders', 'UN', '4 cylinders', '5 cylinders',
       'other', '3 cylinders', '10 cylinders', '12 cylinders'],
      dtype=object)

In [51]:
cylinders = list(df["cylinders"])

In [52]:
len(prices) == len(cylinders)

True

In [53]:
o=0
for i in cylinders:
    
    if i == 'UN':
        if prices[o] <= 1000000.0:
            cylinders[o] = cylinders[o].replace('UN',"12 cylinders")
        elif  prices[o] <=27882.00:
            cylinders[o] = cylinders[o].replace('UN',"10 cylinders")
        elif  prices[o] <= 18935.0:
            cylinders[o] = cylinders[o].replace('UN',"8 cylinders")
        elif  prices[o] <=13995.0:
            cylinders[o] = cylinders[o].replace('UN',"6 cylinders")
        elif  prices[o] <=5995.0:
            cylinders[o] = cylinders[o].replace('UN',"4 cylinders")
        else :
            cylinders[o] = cylinders[o].replace("UN","3 cylinders")
    o+=1


In [54]:
test_4=pd.Series(cylinders)

In [55]:
test_4.unique()

array(['8 cylinders', '6 cylinders', '12 cylinders', '4 cylinders',
       '5 cylinders', 'other', '3 cylinders', '10 cylinders'],
      dtype=object)

In [56]:
df=df.drop(["cylinders"],axis=1)

In [57]:
index =list(df.index)

In [58]:
test_5=pd.DataFrame(cylinders,index=index,columns=["cylinders"])

In [59]:
df=pd.concat([df,test_5],axis=1)

In [60]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer         0
model                0
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147590
drive           112905
size            267055
type             82507
paint_color     106661
description          2
state                0
posting_date         0
condition            0
cylinders            0
dtype: int64

In [61]:
df.sample(5)

region  price    year   manufacturer  \
172526       louisville  26990  2017.0           mini   
318987  medford-ashland   4800  2006.0      chevrolet   
128675           hawaii  46883  2018.0  mercedes-benz   
117115   tampa bay area  19995  2014.0           ford   
82353     western slope   5500  1999.0          rover   

                             model   fuel  odometer title_status transmission  \
172526  hardtop 2 door john cooper  other   24062.0        clean        other   
318987                   silverado    gas  284000.0        clean    automatic   
128675                     e-class    gas   17146.0        clean    automatic   
117115                       f-150    gas  162843.0        clean    automatic   
82353                      hse 4.6    gas  149000.0        clean    automatic   

                      VIN drive       size       type paint_color  \
172526  WMWXM9C30H2F66091   fwd        NaN  hatchback       black   
318987                NaN   4wd  full-size      truck       white   
128675  WDD1J6FB5JF007737   NaN        NaN      coupe        grey   
117115  1FTFW1EFXEKD49819   4wd        NaN     pickup       black   
82353                 NaN   4wd  full-size        SUV      silver   

                                              description state  \
172526  Carvana is the safer way to buy a car During t...    ky   
318987  2006 Chevy Silverado 2500 4x4. 28400 miles. Gr...    or   
128675  2018 Mercedes-Benz E-Class E 400     Offered b...    hi   
117115  2014 Ford F-150 F150 F 150 XLT 4WD SuperCrew 6...    fl   
82353   150,000 miles, rebuilt top end at 141,000..New...    co   

                    posting_date  condition     cylinders  
172526  2021-04-29T20:31:25-0400       good  12 cylinders  
318987  2021-05-04T14:51:35-0700       fair   8 cylinders  
128675  2021-05-01T11:53:58-1000        new  12 cylinders  
117115  2021-05-02T14:35:16-0400        new  12 cylinders  
82353   2021-04-20T21:02:07-0600  excellent   8 cylinders

# drive

In [62]:
df["drive"].unique()

array([nan, 'rwd', '4wd', 'fwd'], dtype=object)

In [63]:
df["drive"]=df["drive"].fillna("UN")
df["drive"].isna().sum()

np.int64(0)

In [64]:
df["drive"].unique()

array(['UN', 'rwd', '4wd', 'fwd'], dtype=object)

In [65]:
drive = list(df["drive"])

In [66]:
len(prices) == len(drive)

True

In [67]:
o=0
for i in drive:
    
    if i == 'UN':
        if prices[o] <= 1000000.0:
            drive[o] = drive[o].replace('UN',"4wd")
        elif  prices[o] <= 18935.0:
            drive[o] = drive[o].replace('UN',"rwd")
        else :
            drive[o] = drive[o].replace("UN","fwd")
    o+=1


In [68]:
test_6=pd.Series(drive)

In [69]:
test_6.unique()

array(['4wd', 'rwd', 'fwd'], dtype=object)

In [70]:
df=df.drop(["drive"],axis=1)

In [71]:
index =list(df.index)

In [72]:
test_7=pd.DataFrame(drive,index=index,columns=["drive"])

In [73]:
df=pd.concat([df,test_7],axis=1)

In [74]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer         0
model                0
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147590
size            267055
type             82507
paint_color     106661
description          2
state                0
posting_date         0
condition            0
cylinders            0
drive                0
dtype: int64

# type

In [75]:
df["type"].unique()

array(['pickup', 'truck', 'other', nan, 'coupe', 'SUV', 'hatchback',
       'mini-van', 'sedan', 'offroad', 'bus', 'convertible', 'wagon',
       'van'], dtype=object)

In [76]:
df["manufacturer"].unique()

array(['gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa-romeo',
       'subaru', 'Unknown', 'acura', 'hyundai', 'mercedes-benz', 'bmw',
       'mitsubishi', 'volkswagen', 'porsche', 'kia', 'ferrari', 'mini',
       'pontiac', 'fiat', 'rover', 'tesla', 'saturn', 'mercury',
       'harley-davidson', 'datsun', 'aston-martin', 'land rover'],
      dtype=object)

In [77]:
manufacturer_type_map = {
    'jeep': 'SUV',
    'land rover': 'SUV',
    'rover': 'SUV',      
    'gmc': 'pickup',    
    'ram': 'pickup',     
    'harley-davidson': 'other', 

    'ferrari': 'coupe',
    'aston-martin': 'coupe',
    'porsche': 'coupe',   
    'alfa-romeo': 'coupe',

    
    'mini': 'hatchback',
    'fiat': 'hatchback',
    'subaru': 'wagon',    

    
    'mercedes-benz': 'sedan',
    'bmw': 'sedan',
    'audi': 'sedan',
    'lexus': 'sedan',
    'cadillac': 'sedan',
    'lincoln': 'sedan',
    'jaguar': 'sedan',
    'infiniti': 'sedan',
    'acura': 'sedan',
    'volvo': 'sedan',
    'buick': 'sedan',
    'chrysler': 'sedan',

    
    'toyota': 'sedan',    
    'honda': 'sedan',     
    'nissan': 'sedan',    
    'ford': 'sedan',      
    'chevrolet': 'sedan', 
    'dodge': 'sedan',   
    'hyundai': 'sedan',
    'kia': 'sedan',
    'mazda': 'sedan',
    'volkswagen': 'sedan',
    'mitsubishi': 'sedan',
    'saturn': 'sedan',
    'mercury': 'sedan',
    'pontiac': 'sedan',
    'datsun': 'sedan',
    'tesla': 'sedan',
    
    'Unknown': 'other'
}



In [78]:
df['type'] = df['type'].fillna(df['manufacturer'].map(manufacturer_type_map))

In [79]:
df['type'].isna().sum()

np.int64(0)

In [80]:
df["type"].unique()

array(['pickup', 'truck', 'other', 'SUV', 'coupe', 'hatchback',
       'mini-van', 'sedan', 'offroad', 'bus', 'convertible', 'wagon',
       'van'], dtype=object)

In [81]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer         0
model                0
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147590
size            267055
type                 0
paint_color     106661
description          2
state                0
posting_date         0
condition            0
cylinders            0
drive                0
dtype: int64

# size

In [82]:
df["size"].unique()

array([nan, 'full-size', 'mid-size', 'compact', 'sub-compact'],
      dtype=object)

In [83]:
type_size_map = {
    'sedan': 'mid-size',
    'coupe': 'compact',      
    'hatchback': 'sub-compact',
    'SUV': 'full-size',     
    'pickup': 'full-size',
    'truck': 'full-size',
    'van': 'full-size',
    'mini-van': 'mid-size',
    'wagon': 'mid-size',
    'bus': 'full-size',
    'offroad': 'full-size',
    'convertible': 'compact',
    'other' : 'UNKNOWN'
} 

In [84]:
df['size'] = df['size'].fillna(df['type'].map(type_size_map))

In [85]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer         0
model                0
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147590
size                 0
type                 0
paint_color     106661
description          2
state                0
posting_date         0
condition            0
cylinders            0
drive                0
dtype: int64

# paint_color

In [86]:
df["paint_color"] = df["paint_color"].fillna("UNKNOWN")  

In [87]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer         0
model                0
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147590
size                 0
type                 0
paint_color          0
description          2
state                0
posting_date         0
condition            0
cylinders            0
drive                0
dtype: int64

# description

In [88]:
df.dropna(subset=["description"],inplace = True)

In [89]:
df.isna().sum()

region               0
price                0
year                 0
manufacturer         0
model                0
fuel                 0
odometer             0
title_status         0
transmission         0
VIN             147589
size                 0
type                 0
paint_color          0
description          0
state                0
posting_date         0
condition            0
cylinders            0
drive                0
dtype: int64

# VIN

In [90]:
df["VIN"] = df["VIN"].fillna("UNKNOWN")  

In [91]:
df.isna().sum()

region          0
price           0
year            0
manufacturer    0
model           0
fuel            0
odometer        0
title_status    0
transmission    0
VIN             0
size            0
type            0
paint_color     0
description     0
state           0
posting_date    0
condition       0
cylinders       0
drive           0
dtype: int64

In [92]:
df.sample(5)

region  price    year   manufacturer                    model  \
337097      pittsburgh  35590  2014.0         jaguar  f-type v8 s convertible   
12799         prescott   2500  1946.0           ford                    coupe   
68582   ventura county  20990  2014.0  mercedes-benz        glk-class glk 350   
151319    indianapolis  13600  2011.0          honda                cr-v ex-l   
97616      gainesville  29590  2019.0     alfa-romeo   romeo stelvio ti sport   

         fuel  odometer title_status transmission                VIN  \
337097    gas   76372.0        clean        other  SAJWA6GL8EMK00863   
12799     gas  100000.0        clean        other            UNKNOWN   
68582     gas   58814.0        clean    automatic  WDCGG8JB3EG322732   
151319    gas   75075.0        clean    automatic            UNKNOWN   
97616   other   60984.0        clean        other  ZASPAKBN6K7C33284   

               size       type paint_color  \
337097      UNKNOWN      other       black   
12799       compact      coupe     UNKNOWN   
68582     full-size        SUV       white   
151319     mid-size        SUV        blue   
97616   sub-compact  hatchback       black   

                                              description state  \
337097  Carvana is the safer way to buy a car During t...    pa   
12799   1946 Ford coupe.  Pretty much body and frame. ...    az   
68582   Carvana is the safer way to buy a car During t...    ca   
151319  2011 Honda CRV- with 75, 075 miles  Excellent ...    in   
97616   Carvana is the safer way to buy a car During t...    fl   

                    posting_date  condition     cylinders drive  
337097  2021-04-22T14:40:41-0400       good   8 cylinders   rwd  
12799   2021-05-02T12:38:13-0700       fair         other   rwd  
68582   2021-04-11T04:01:05-0700       good   6 cylinders   4wd  
151319  2021-05-03T22:51:10-0400  excellent   4 cylinders   4wd  
97616   2021-04-08T08:21:18-0400       good  12 cylinders   4wd

# VIN
# description
# posting_date

In [93]:
df['posting_date'] = pd.to_datetime(df['posting_date'], utc=True)

df['posting_month'] = df['posting_date'].dt.month
df['posting_day'] = df['posting_date'].dt.day
df['posting_weekday'] = df['posting_date'].dt.weekday 
df['posting_day'] = df['posting_date'].dt.day_name()

In [94]:
df

region  price    year manufacturer                     model    fuel  \
27       auburn  33590  2014.0          gmc  sierra 1500 crew cab slt     gas   
28       auburn  22590  2010.0    chevrolet            silverado 1500     gas   
29       auburn  39590  2020.0    chevrolet       silverado 1500 crew     gas   
30       auburn  30990  2017.0       toyota      tundra double cab sr     gas   
31       auburn  15000  2013.0         ford                 f-150 xlt     gas   
...         ...    ...     ...          ...                       ...     ...   
426875  wyoming  23590  2019.0       nissan         maxima s sedan 4d     gas   
426876  wyoming  30590  2020.0        volvo  s60 t5 momentum sedan 4d     gas   
426877  wyoming  34990  2020.0     cadillac          xt4 sport suv 4d  diesel   
426878  wyoming  28990  2018.0        lexus           es 350 sedan 4d     gas   
426879  wyoming  30590  2019.0          bmw  4 series 430i gran coupe     gas   

        odometer title_status transmission                VIN  ...  \
27       57923.0        clean        other  3GTP1VEC4EG551563  ...   
28       71229.0        clean        other  1GCSCSE06AZ123805  ...   
29       19160.0        clean        other  3GCPWCED5LG130317  ...   
30       41124.0        clean        other  5TFRM5F17HX120972  ...   
31      128000.0        clean    automatic            UNKNOWN  ...   
...          ...          ...          ...                ...  ...   
426875   32226.0        clean        other  1N4AA6AV6KC367801  ...   
426876   12029.0        clean        other  7JR102FKXLG042696  ...   
426877    4174.0        clean        other  1GYFZFR46LF088296  ...   
426878   30112.0        clean        other  58ABK1GG4JU103853  ...   
426879   22716.0        clean        other  WBA4J1C58KBM14708  ...   

       paint_color                                        description state  \
27           white  Carvana is the safer way to buy a car During t...    al   
28            blue  Carvana is the safer way to buy a car During t...    al   
29             red  Carvana is the safer way to buy a car During t...    al   
30             red  Carvana is the safer way to buy a car During t...    al   
31           black  2013 F-150 XLT V6 4 Door. Good condition. Leve...    al   
...            ...                                                ...   ...   
426875     UNKNOWN  Carvana is the safer way to buy a car During t...    wy   
426876         red  Carvana is the safer way to buy a car During t...    wy   
426877       white  Carvana is the safer way to buy a car During t...    wy   
426878      silver  Carvana is the safer way to buy a car During t...    wy   
426879     UNKNOWN  Carvana is the safer way to buy a car During t...    wy   

                    posting_date  condition     cylinders drive posting_month  \
27     2021-05-04 17:31:18+00:00       good   8 cylinders   4wd             5   
28     2021-05-04 17:31:08+00:00       good   8 cylinders   4wd             5   
29     2021-05-04 17:31:25+00:00       good   8 cylinders   4wd             5   
30     2021-05-04 15:41:31+00:00       good   8 cylinders   4wd             5   
31     2021-05-03 19:02:03+00:00  excellent   6 cylinders   rwd             5   
...                          ...        ...           ...   ...           ...   
426875 2021-04-04 09:21:31+00:00       good   6 cylinders   fwd             4   
426876 2021-04-04 09:21:29+00:00       good  12 cylinders   fwd             4   
426877 2021-04-04 09:21:17+00:00       good  12 cylinders   4wd             4   
426878 2021-04-04 09:21:11+00:00       good   6 cylinders   fwd             4   
426879 2021-04-04 09:21:07+00:00       good  12 cylinders   rwd             4   

       posting_day  posting_weekday  
27         Tuesday                1  
28         Tuesday                1  
29         Tuesday                1  
30         Tuesday                1  
31          Monday                0  
...            ...              ...  
426875 

In [95]:
df['has_phone'] = df['description'].str.contains(r'\d{3}-\d{3}-\d{4}', regex=True).astype(int)
df['desc_word_count'] = df['description'].apply(lambda x: len(str(x).split()))
df['has_warranty'] = df['description'].str.contains('warranty', case=False).astype(int)
df['is_one_owner'] = df['description'].str.contains('one owner|1st owner', case=False).astype(int)

In [102]:
df["has_phone"].unique()

array([1, 0])

In [103]:
df["desc_word_count"].unique()

array([ 681,  692,  690, ..., 2870, 2781, 2934])

In [104]:
df["has_warranty"].unique()

array([0, 1])

In [105]:
df["is_one_owner"].unique()

array([0, 1])

In [106]:
df['vin_country_code'] = df['VIN'].apply(lambda x: x[0] if x != "UNKNOWN" else "UNKNOWN")

In [107]:
country_map = {'1': 'USA', '4': 'USA', '5': 'USA', 'J': 'Japan', 'K': 'South Korea', 'W': 'Germany'}

In [108]:
df['origin_country'] = df['vin_country_code'].map(country_map).fillna('Other/Unknown')

In [109]:
df['origin_country'] 

27        Other/Unknown
28                  USA
29        Other/Unknown
30                  USA
31        Other/Unknown
              ...      
426875              USA
426876    Other/Unknown
426877              USA
426878              USA
426879          Germany
Name: origin_country, Length: 375715, dtype: object

# Columns Cleaning

In [110]:
df.columns

Index(['region', 'price', 'year', 'manufacturer', 'model', 'fuel', 'odometer',
       'title_status', 'transmission', 'VIN', 'size', 'type', 'paint_color',
       'description', 'state', 'posting_date', 'condition', 'cylinders',
       'drive', 'posting_month', 'posting_day', 'posting_weekday', 'has_phone',
       'desc_word_count', 'has_warranty', 'is_one_owner', 'vin_country_code',
       'origin_country'],
      dtype='object')

 ### Region

In [111]:
df["region"].sample(43)

64840                       stockton
219901          columbia / jeff city
376939    killeen / temple / ft hood
96947                    gainesville
44489                   palm springs
284016                 new hampshire
270588                 hudson valley
113203                 south florida
110340            sarasota-bradenton
215088         minneapolis / st paul
365457                        austin
90293                 washington, DC
166617               kansas city, MO
117472                tampa bay area
405526                    moses lake
13442                       prescott
258665                  south jersey
38572                        modesto
116707                tampa bay area
350677          rapid city / west SD
376484                       houston
37529                        modesto
356422                     knoxville
299627          dayton / springfield
312288                          bend
37530                        modesto
65625                       stockton
2

In [112]:
df["region"]=df["region"].replace([",","/","'","-","  "]," ",regex=True)


In [113]:
df["region"].sample(200)

140534               chicago
205834               lansing
257337          south jersey
266287            binghamton
308956                 tulsa
                 ...        
307067         oklahoma city
183800             baltimore
278365             rochester
61143            SF bay area
221423    southeast missouri
Name: region, Length: 200, dtype: object

### Price

In [114]:
df["price"].dtypes

dtype('int64')

### Year

In [115]:
df["year"].dtypes

dtype('float64')

In [116]:
df["year"] = df["year"].astype(int) 

In [117]:
df["year"].dtypes

dtype('int64')

In [118]:
df["year"].unique

<bound method Series.unique of 27        2014
28        2010
29        2020
30        2017
31        2013
          ... 
426875    2019
426876    2020
426877    2020
426878    2018
426879    2019
Name: year, Length: 375715, dtype: int64>

### Manufacturer

In [119]:
df["manufacturer"].unique()

array(['gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa-romeo',
       'subaru', 'Unknown', 'acura', 'hyundai', 'mercedes-benz', 'bmw',
       'mitsubishi', 'volkswagen', 'porsche', 'kia', 'ferrari', 'mini',
       'pontiac', 'fiat', 'rover', 'tesla', 'saturn', 'mercury',
       'harley-davidson', 'datsun', 'aston-martin', 'land rover'],
      dtype=object)

In [120]:
df["manufacturer"] = df["manufacturer"].replace(["-"]," ",regex=True)

In [121]:
df["manufacturer"].unique()

array(['gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa romeo',
       'subaru', 'Unknown', 'acura', 'hyundai', 'mercedes benz', 'bmw',
       'mitsubishi', 'volkswagen', 'porsche', 'kia', 'ferrari', 'mini',
       'pontiac', 'fiat', 'rover', 'tesla', 'saturn', 'mercury',
       'harley davidson', 'datsun', 'aston martin', 'land rover'],
      dtype=object)

In [122]:
df["manufacturer"].dtypes

dtype('O')

### Model

In [123]:
df["model"].unique()

array(['sierra 1500 crew cab slt', 'silverado 1500',
       'silverado 1500 crew', ..., 'gand wagoneer', '96 Suburban',
       'Paige Glenbrook Touring'], dtype=object)

In [124]:
df["model"].sample(50)

350471                                      f250 super duty
134197                                                 1500
252785                                                scion
295124                                                 soul
400659                                 4 series 435i xdrive
224462                                                 xc70
158166                                     silverado 3500hd
121067                                              odyssey
26251     2500 6.7 cummins diesel 4x4 laramie lifted on 37s
107855                                          pickup 1500
122775                                    titan xd crew cab
358428                              encore sport utility 4d
365946                                           avalon xls
346709                             e-pace p300 r-dynamic se
6490                                                   430i
63454                                           ranchero gt
209108                           wrangle

In [125]:
df=df.drop(["model"],axis = 1)

In [126]:
df.columns

Index(['region', 'price', 'year', 'manufacturer', 'fuel', 'odometer',
       'title_status', 'transmission', 'VIN', 'size', 'type', 'paint_color',
       'description', 'state', 'posting_date', 'condition', 'cylinders',
       'drive', 'posting_month', 'posting_day', 'posting_weekday', 'has_phone',
       'desc_word_count', 'has_warranty', 'is_one_owner', 'vin_country_code',
       'origin_country'],
      dtype='object')

### Fuel

In [127]:
df["fuel"].unique()

array(['gas', 'other', 'diesel', 'hybrid', 'electric'], dtype=object)

### Odometer

In [128]:
df["odometer"].dtypes

dtype('float64')

In [129]:
df["odometer"]=df["odometer"].round()

In [130]:
df["odometer"] = df["odometer"].astype(int)

In [131]:
df["odometer"].dtypes

dtype('int64')

### Title_status

In [132]:
df["title_status"].unique()

array(['clean', 'rebuilt', 'lien', 'salvage', 'missing', 'parts only'],
      dtype=object)

### Transmission

In [133]:
df["transmission"].unique()

array(['other', 'automatic', 'manual'], dtype=object)

### VIN

In [134]:
df["VIN"].unique()

array(['3GTP1VEC4EG551563', '1GCSCSE06AZ123805', '3GCPWCED5LG130317', ...,
       '2HGES15535H620534', '1FDWF37P64EA24868', 'SAJGX2749VCOO8376'],
      dtype=object)

In [135]:
df=df.drop(["VIN"],axis=1)

In [136]:
df.columns

Index(['region', 'price', 'year', 'manufacturer', 'fuel', 'odometer',
       'title_status', 'transmission', 'size', 'type', 'paint_color',
       'description', 'state', 'posting_date', 'condition', 'cylinders',
       'drive', 'posting_month', 'posting_day', 'posting_weekday', 'has_phone',
       'desc_word_count', 'has_warranty', 'is_one_owner', 'vin_country_code',
       'origin_country'],
      dtype='object')

### Size

In [137]:
df["size"].unique()

array(['full-size', 'UNKNOWN', 'compact', 'sub-compact', 'mid-size'],
      dtype=object)

In [138]:
df["size"]=df["size"].replace("-"," ",regex=True)

### Type

In [139]:
df["type"].unique()

array(['pickup', 'truck', 'other', 'SUV', 'coupe', 'hatchback',
       'mini-van', 'sedan', 'offroad', 'bus', 'convertible', 'wagon',
       'van'], dtype=object)

In [140]:
df["type"]=df["type"].replace("-"," ",regex=True)

### Paint_color

In [141]:
df["paint_color"].unique()

array(['white', 'blue', 'red', 'black', 'silver', 'grey', 'UNKNOWN',
       'brown', 'yellow', 'orange', 'green', 'custom', 'purple'],
      dtype=object)

### Description

In [142]:
df=df.drop(["description"],axis=1)

In [143]:
df.columns

Index(['region', 'price', 'year', 'manufacturer', 'fuel', 'odometer',
       'title_status', 'transmission', 'size', 'type', 'paint_color', 'state',
       'posting_date', 'condition', 'cylinders', 'drive', 'posting_month',
       'posting_day', 'posting_weekday', 'has_phone', 'desc_word_count',
       'has_warranty', 'is_one_owner', 'vin_country_code', 'origin_country'],
      dtype='object')

### State

In [144]:
df["state"].unique()

array(['al', 'ak', 'az', 'ar', 'ca', 'co', 'ct', 'dc', 'de', 'fl', 'ga',
       'hi', 'id', 'il', 'in', 'ia', 'ks', 'ky', 'la', 'me', 'md', 'ma',
       'mi', 'mn', 'ms', 'mo', 'mt', 'nc', 'ne', 'nv', 'nj', 'nm', 'ny',
       'nh', 'nd', 'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx',
       'ut', 'vt', 'va', 'wa', 'wv', 'wi', 'wy'], dtype=object)

### Posting_date

In [145]:
df=df.drop(["posting_date"],axis =1)

In [146]:
df.columns

Index(['region', 'price', 'year', 'manufacturer', 'fuel', 'odometer',
       'title_status', 'transmission', 'size', 'type', 'paint_color', 'state',
       'condition', 'cylinders', 'drive', 'posting_month', 'posting_day',
       'posting_weekday', 'has_phone', 'desc_word_count', 'has_warranty',
       'is_one_owner', 'vin_country_code', 'origin_country'],
      dtype='object')

### Condition

In [147]:
df["condition"].unique()

array(['good', 'excellent', 'fair', 'like new', 'new', 'salvage'],
      dtype=object)

### Cylinders

In [148]:
df["cylinders"].unique()

array(['8 cylinders', '6 cylinders', '12 cylinders', '4 cylinders',
       '5 cylinders', 'other', '3 cylinders', '10 cylinders'],
      dtype=object)

### Drive

In [149]:
df["drive"].unique()

array(['4wd', 'rwd', 'fwd'], dtype=object)

### posting_month

In [150]:
df["posting_month"].unique()

array([5, 4], dtype=int32)

### Posting_day

In [151]:
df["posting_day"].unique()

array(['Tuesday', 'Monday', 'Sunday', 'Saturday', 'Friday', 'Thursday',
       'Wednesday'], dtype=object)

### Posting_weekday

In [152]:
df["posting_weekday"].unique()

array([1, 0, 6, 5, 4, 3, 2], dtype=int32)

### Has_phone

In [153]:
df["has_phone"].unique()

array([1, 0])

In [163]:
df["has_phone"] =df["has_phone"].replace(0,"Not Has")
df["has_phone"] =df["has_phone"].replace(1,"Has")

In [164]:
df["has_phone"].unique()

array(['Has', 'Not Has'], dtype=object)

In [165]:
df["has_phone"].dtypes

dtype('O')

### Desc_word_count

In [166]:
df["desc_word_count"].unique()

array([ 681,  692,  690, ..., 2870, 2781, 2934])

In [167]:
df["desc_word_count"].dtypes

dtype('int64')

### Has_warranty

In [160]:
df["has_warranty"].unique()

array([0, 1])

In [168]:
df["has_warranty"] =df["has_warranty"].replace(0,"Not Warranty")
df["has_warranty"] =df["has_warranty"].replace(1,"Warranty")

In [169]:
df["has_warranty"].unique()

array(['Not Warranty', 'Warranty'], dtype=object)

### Is_one_owner

In [220]:
df["is_one_owner"].unique()

array([0, 1])

In [170]:
df["is_one_owner"] =df["is_one_owner"].replace(0,"Other")
df["is_one_owner"] =df["is_one_owner"].replace(1,"One Owner")

In [171]:
df["is_one_owner"].unique()

array(['Other', 'One Owner'], dtype=object)

### Vin_country_code

In [172]:
df["vin_country_code"].unique()

array(['3', '1', '5', 'UNKNOWN', 'J', 'Z', '2', 'S', 'K', 'Y', '7', 'W',
       'L', '4', 'N', '0', 'B', 'M', '6', 'T', 'H', 'C', 'D', 'V', 'P',
       '8', 'I', 'F', 'A', 'U', '9', 'R', 'G', 'X', 'E', 'O'],
      dtype=object)

In [173]:
df.columns

Index(['region', 'price', 'year', 'manufacturer', 'fuel', 'odometer',
       'title_status', 'transmission', 'size', 'type', 'paint_color', 'state',
       'condition', 'cylinders', 'drive', 'posting_month', 'posting_day',
       'posting_weekday', 'has_phone', 'desc_word_count', 'has_warranty',
       'is_one_owner', 'vin_country_code', 'origin_country'],
      dtype='object')

### Origin_country

In [174]:
df["origin_country"].unique()

array(['Other/Unknown', 'USA', 'Japan', 'South Korea', 'Germany'],
      dtype=object)

In [175]:
df["origin_country"]=df["origin_country"].replace(["/Unknown"],"",regex= True)

In [176]:
df["origin_country"].unique()

array(['Other', 'USA', 'Japan', 'South Korea', 'Germany'], dtype=object)

# Reset index

In [177]:
df = df.reset_index(drop=True)

In [178]:
df.sample()

region  price  year manufacturer fuel  odometer title_status  \
157169  maine   6995  2012         jeep  gas       173        clean   

       transmission       size type  ... drive posting_month posting_day  \
157169    automatic  full size  SUV  ...   4wd             4      Friday   

       posting_weekday has_phone  desc_word_count has_warranty  is_one_owner  \
157169               4       Has              195     Warranty         Other   

       vin_country_code  origin_country  
157169          UNKNOWN           Other  

[1 rows x 24 columns]

# Export New Data 

In [180]:
df.to_csv("D:/projects/USED_CAR/vehicles.csv/New_Data.csv")

In [181]:
df.columns

Index(['region', 'price', 'year', 'manufacturer', 'fuel', 'odometer',
       'title_status', 'transmission', 'size', 'type', 'paint_color', 'state',
       'condition', 'cylinders', 'drive', 'posting_month', 'posting_day',
       'posting_weekday', 'has_phone', 'desc_word_count', 'has_warranty',
       'is_one_owner', 'vin_country_code', 'origin_country'],
      dtype='object')